### ISSUE TITLE
pre-commit hook does not work

### ISSUE THREAD

**Issue by new-cassellito** [belav/csharpier#820]
https://csharpier.com/docs/Pre-commit says you can use csharpier with pre-commit, but this functionality doesn't work - after including the csharpier hook as per the instructions, the hook fails to install:

```
$ pre-commit run
[INFO] Installing environment for https://github.com/belav/csharpier.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('C:\\Program Files\\dotnet\\dotnet.EXE', 'tool', 'install', '--configfile', 'C:\\Users\\Lucas\\AppData\\Local\\Temp\\tmpcrqgampz\\nuget.config', '--tool-path', 'C:\\Users\\Lucas\\.cache\\pre-commit\\reponbup7ntf\\dotnetenv-default\\bin', '--add-source', 'pre-commit-build', 'CSharpier.Benchmarks')
return code: 1
stdout:
    C:\Users\Lucas\AppData\Local\Temp\a04c5a0c-40b7-4cba-8cc4-c616ccf96459\restore.csproj : error NU1101: Unable to find package BenchmarkDotNet. No packages exist with this id in source(s): C:\Users\Lucas\.cache\pre-commit\reponbup7ntf\pre-commit-build
    C:\Users\Lucas\AppData\Local\Temp\a04c5a0c-40b7-4cba-8cc4-c616ccf96459\restore.csproj : error NU1101: Unable to find package BenchmarkDotNet.Annotations. No packages exist with this id in source(s): C:\Users\Lucas\.cache\pre-commit\reponbup7ntf\pre-commit-build
    C:\Users\Lucas\AppData\Local\Temp\a04c5a0c-40b7-4cba-8cc4-c616ccf96459\restore.csproj : error NU1101: Unable to find package Microsoft.CodeAnalysis.CSharp. No packages exist with this id in source(s): C:\Users\Lucas\.cache\pre-commit\reponbup7ntf\pre-commit-build
    C:\Users\Lucas\AppData\Local\Temp\a04c5a0c-40b7-4cba-8cc4-c616ccf96459\restore.csproj : error NU1101: Unable to find package System.IO.Abstractions. No packages exist with this id in source(s): C:\Users\Lucas\.cache\pre-commit\reponbup7ntf\pre-commit-build
    C:\Users\Lucas\AppData\Local\Temp\a04c5a0c-40b7-4cba-8cc4-c616ccf96459\restore.csproj : error NU1101: Unable to find package System.Text.Json. No packages exist with this id in source(s): C:\Users\Lucas\.cache\pre-commit\reponbup7ntf\pre-commit-build

stderr:
    The tool package could not be restored.
    Tool 'csharpier.benchmarks' failed to install. This failure may have been caused by:

    * You are attempting to install a preview release and did not use the --version option to specify the version.
    * A package by this name was found, but it was not a .NET tool.
    * The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
    * You mistyped the name of the tool.

    For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

Check the log at C:\Users\Lucas\.cache\pre-commit\pre-commit.log
```

**Comment by new-cassellito** [comment]
@Kurt-von-Laven i see it was your pr #798 that added this. is there something else you did to get it working that you didn't put in the instructions?

**Comment by Kurt-von-Laven** [comment]
We had been running CSharpier via a local pre-commit hook successfully, but it looks like pre-commit is running into issues installing CSharpier's dependencies while trying to build it when the hook is remote rather than local. According to [pre-commit's official documentation](https://pre-commit.com/#dotnet):

> Additional dependencies are not currently supported.

CSharpier unfortunately cannot be run as a remote pre-commit hook until pre-commit adds support for additional dependencies for .NET hooks. Since CSharpier was recently added to [MegaLinter](https://megalinter.io/), we now run CSharpier via [MegaLinter's pre-commit hook](https://megalinter.io/latest/mega-linter-runner/#pre-commit-hook) instead. This was how we ran CSharpier via a local pre-commit hook though in case it's helpful:

In `.pre-commit-config.yaml`:

```yaml
repos:
  - repo: local
    hooks:
      - id: dotnet-tool-restore
        name: Install .NET Core tools
        entry: dotnet tool restore
        language: system
        always_run: true
        pass_filenames: false
        stages:
          - commit
          - push
          - post-checkout
          - post-rewrite
        description: Install the tools listed at .config/dotnet-tools.json.
      - id: csharpier
        name: Run CSharpier on C# files
        entry: dotnet tool run dotnet-csharpier
        language: system
        types:
          - c#
        description: CSharpier is an opinionated C# formatter inspired by Prettier.
```

In `.config/dotnet-tools.json`:

```json
{
  "tools": {
    "CSharpier": {
      "version": "0.22.1",
      "commands": ["dotnet-csharpier"]
    }
  }
}
```

I'll open a pull request to remove the pre-commit hook from this repository for now. Thanks for reporting this issue, @new-cassellito.
