### ISSUE TITLE
Mutliline comments always indented with spaces

### ISSUE THREAD

**Issue by MonstraG** [belav/csharpier#891]
```cs
public class Foo
{
	/**
	 * comment
	 */
	public class Bar { }
}
```
=>

```cs
public class Foo
{
 /**
  * comment
  */
	public class Bar { }
}
```

.csharpierrc.yaml
```yml
printWidth: 100
useTabs: true
tabWidth: 4
```

Btw, there is no way to check this on playground because it's always in spaces mode.
